Repository cau-likelion-org/kiwi-server, pull requests merged in 2023-12, with the labels that each got.

#2 feat: 구글 로그인, 회원가입, 닉네임 중복확인
  config/settings.py
  config/urls.py
  requirements.txt
  users/__init__.py
  users/admin.py
  users/apps.py
  users/models.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: feat

#8 feat: 랜덤 닉네임 부여
  .gitignore
  users/urls.py
  users/views.py
Labels: feat

#12 feat: 문자열 간 비교 로직 작성
  documents/service.py
Labels: feat

#16 Feat/#4 문서 생성, 조회 기능
  config/urls.py
  documents/models.py
  documents/serializers.py
  documents/urls.py
  documents/views.py
Labels: feat

#17 feat: 임의 문서 조회, 기수별 필터링, 검색
  documents/urls.py
  documents/views.py
Labels: feat

#21 feat: docs backlink
  documents/serializers.py
  documents/urls.py
  documents/views.py
Labels: feat

#22 feat: 이미지 url 반환 기능
  config/settings.py
  documents/serializers.py
  documents/urls.py
  documents/views.py
  requirements.txt
Labels: feat

#25 chore: 이미지 api명세랑 일치하게 수정
  documents/serializers.py
  documents/views.py
Labels: document

#27 fix: updated pyopenssl
  requirements.txt
Labels: bug, fix

#28 chore: generation 모델 수정
  documents/models.py
  documents/urls.py
Labels: document

#32 chore: backlink 검색 url 변경
  documents/views.py
Labels: fix, document
